/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package org.iotashan.apphelper;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.app.Activity;
import android.content.ActivityNotFoundException;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.content.pm.PackageManager.NameNotFoundException;
//import android.os.Bundle;

@Kroll.module(name="Apphelper", id="org.iotashan.apphelper")
public class ApphelperModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "ApphelperModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public ApphelperModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public Boolean isAppInstalled(String appID)
	{
		final Intent mainIntent = new Intent(Intent.ACTION_MAIN, null);
		mainIntent.addCategory(Intent.CATEGORY_LAUNCHER);
		
		Activity activity = getActivity();
		if (activity == null) {
			Log.d(LCAT, "getActivity() returned null");
			return false;
		}
		
		Context ctx = activity.getBaseContext();
		if (ctx == null) {
			Log.d(LCAT, "getBaseContext() returned null");
			return false;
		}
		
		PackageManager packageManager = ctx.getPackageManager();
		if (packageManager == null) {
			Log.d(LCAT, "getPackageManager() returned null");
			return false;
		}
		
		Boolean installed = false;
		
		try {
			PackageInfo info = packageManager.getPackageInfo(appID, 0);

			if(null != info) {
				installed = true;
			}
		} catch (NameNotFoundException e) {
			Log.d(LCAT, "NameNotFoundException");
		}
		
		return installed;
	}
    
	@Kroll.method
	public void openAppByID(String appID)
	{
		final Intent mainIntent = new Intent(Intent.ACTION_MAIN, null);
		mainIntent.addCategory(Intent.CATEGORY_LAUNCHER);
		
		Activity activity = getActivity();
		if (activity == null) {
			Log.d(LCAT, "getActivity() returned null");
			return;
		}
		
		Context ctx = activity.getBaseContext();
		if (ctx == null) {
			Log.d(LCAT, "getBaseContext() returned null");
			return;
		}
		
		PackageManager packageManager = ctx.getPackageManager();
		if (packageManager == null) {
			Log.d(LCAT, "getPackageManager() returned null");
			return;
		}
		
		try {
			Intent intent = packageManager.getLaunchIntentForPackage(appID);
            
			if(null != intent) {
				ctx.startActivity(intent);
			}
		} catch (ActivityNotFoundException e) {
			Log.d(LCAT, "ActivityNotFoundException");
		}
	}
    
	@Kroll.method
	public Boolean hasMainCamera()
	{
		final Intent mainIntent = new Intent(Intent.ACTION_MAIN, null);
		mainIntent.addCategory(Intent.CATEGORY_LAUNCHER);
		
		Activity activity = getActivity();
		if (activity == null) {
			Log.d(LCAT, "getActivity() returned null");
			return false;
		}
		
		Context ctx = activity.getBaseContext();
		if (ctx == null) {
			Log.d(LCAT, "getBaseContext() returned null");
			return false;
		}
		
		PackageManager packageManager = ctx.getPackageManager();
		if (packageManager == null) {
			Log.d(LCAT, "getPackageManager() returned null");
			return false;
		}
		
		return packageManager.hasSystemFeature(PackageManager.FEATURE_CAMERA);
	}
	
	// Properties
}

